# Generated by Django 5.0.1 on 2024-02-02 07:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cabinet", "0005_auto_20190415_0343"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="folder",
            unique_together=set(),
        ),
    ]
